@echo off
cd /d "C:\Users\ปิ๊ก\.gemini\antigravity\scratch\nyxcable-website\sanity"
set SANITY_TOKEN=skkAQFO5bMw9B1gGCMwt9r7vBjm7QoXiBcnuEcEr64cIhomU5o0hKRq5ag8yMISz6tvFT4P1EanhMCyRt6G80xbEL73TXtkU3Ts3YLCLPT5zRpDkGXlxCjopjPXHaaHaxhhMjWnzfKQo5yJONvpHLkbdNk3d1DHMbyHQbXQ6W3febOS1oYBn
node scripts/set-product-order.mjs
pause
